// Code generated by "stringer -type=VehicleModType"; DO NOT EDIT.

package vehicle_mod_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Spoilers-0]
	_ = x[FrontBumper-1]
	_ = x[RearBumper-2]
	_ = x[SideSkirt-3]
	_ = x[Exhaust-4]
	_ = x[Frame-5]
	_ = x[Grille-6]
	_ = x[Hood-7]
	_ = x[Fender-8]
	_ = x[RightFender-9]
	_ = x[Roof-10]
	_ = x[Engine-11]
	_ = x[Brakes-12]
	_ = x[Transmission-13]
	_ = x[Horns-14]
	_ = x[Suspension-15]
	_ = x[Armor-16]
}

const _VehicleModType_name = "SpoilersFrontBumperRearBumperSideSkirtExhaustFrameGrilleHoodFenderRightFenderRoofEngineBrakesTransmissionHornsSuspensionArmor"

var _VehicleModType_index = [...]uint8{0, 8, 19, 29, 38, 45, 50, 56, 60, 66, 77, 81, 87, 93, 105, 110, 120, 125}

func (i VehicleModType) String() string {
	if i >= VehicleModType(len(_VehicleModType_index)-1) {
		return "VehicleModType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VehicleModType_name[_VehicleModType_index[i]:_VehicleModType_index[i+1]]
}
