// Code generated by "stringer -type=WeatherType"; DO NOT EDIT.

package weather

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExtraSunny-0]
	_ = x[Clear-1]
	_ = x[Clouds-2]
	_ = x[Smog-3]
	_ = x[Foggy-4]
	_ = x[Overcast-5]
	_ = x[Rain-6]
	_ = x[Thunder-7]
	_ = x[Clearing-8]
	_ = x[Neutral-9]
	_ = x[Snow-10]
	_ = x[Blizzard-11]
	_ = x[Snowlight-12]
	_ = x[Xmas-13]
	_ = x[Halloween-14]
}

const _WeatherType_name = "ExtraSunnyClearCloudsSmogFoggyOvercastRainThunderClearingNeutralSnowBlizzardSnowlightXmasHalloween"

var _WeatherType_index = [...]uint8{0, 10, 15, 21, 25, 30, 38, 42, 49, 57, 64, 68, 76, 85, 89, 98}

func (i WeatherType) String() string {
	if i >= WeatherType(len(_WeatherType_index)-1) {
		return "WeatherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WeatherType_name[_WeatherType_index[i]:_WeatherType_index[i+1]]
}
