// Code generated by "stringer -type=RadioStation"; DO NOT EDIT.

package radio_station_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LosSantosRockRadio-0]
	_ = x[NonStopPopFm-1]
	_ = x[RadioLosSantos-2]
	_ = x[ChannelX-3]
	_ = x[WestCoastTalkRadio-4]
	_ = x[RebelRadio-5]
	_ = x[SoulwaxFm-6]
	_ = x[EastLosFm-7]
	_ = x[WestCoastClassics-8]
	_ = x[BlaineCountyRadio-9]
	_ = x[TheBlueArk-10]
	_ = x[WorldWideFm-11]
	_ = x[FlyloFm-12]
	_ = x[TheLowdown-13]
	_ = x[RadioMirrorPark-14]
	_ = x[Space-15]
	_ = x[VinewoodBoulevardRadio-16]
	_ = x[SelfRadio-17]
	_ = x[TheLab-18]
	_ = x[RadioOff-255]
}

const (
	_RadioStation_name_0 = "LosSantosRockRadioNonStopPopFmRadioLosSantosChannelXWestCoastTalkRadioRebelRadioSoulwaxFmEastLosFmWestCoastClassicsBlaineCountyRadioTheBlueArkWorldWideFmFlyloFmTheLowdownRadioMirrorParkSpaceVinewoodBoulevardRadioSelfRadioTheLab"
	_RadioStation_name_1 = "RadioOff"
)

var (
	_RadioStation_index_0 = [...]uint8{0, 18, 30, 44, 52, 70, 80, 89, 98, 115, 132, 142, 153, 160, 170, 185, 190, 212, 221, 227}
)

func (i RadioStation) String() string {
	switch {
	case i <= 18:
		return _RadioStation_name_0[_RadioStation_index_0[i]:_RadioStation_index_0[i+1]]
	case i == 255:
		return _RadioStation_name_1
	default:
		return "RadioStation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
