// Code generated by "stringer -type=NumberPlateStyle"; DO NOT EDIT.

package numplate_style_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BlueWhite-0]
	_ = x[YellowBlack-1]
	_ = x[YellowBlue-2]
	_ = x[BlueWhite2-3]
	_ = x[BlueWhite3-4]
	_ = x[Yankton-5]
}

const _NumberPlateStyle_name = "BlueWhiteYellowBlackYellowBlueBlueWhite2BlueWhite3Yankton"

var _NumberPlateStyle_index = [...]uint8{0, 9, 20, 30, 40, 50, 57}

func (i NumberPlateStyle) String() string {
	if i < 0 || i >= NumberPlateStyle(len(_NumberPlateStyle_index)-1) {
		return "NumberPlateStyle(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumberPlateStyle_name[_NumberPlateStyle_index[i]:_NumberPlateStyle_index[i+1]]
}
