// Code generated by "stringer -type=ModelHash"; DO NOT EDIT.

package weapon_hash

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AntiqueCavalryDagger-2460120199]
	_ = x[BaseballBat-2508868239]
	_ = x[BrokenBottle-4192643659]
	_ = x[Crowbar-2227010557]
	_ = x[Fist-2725352035]
	_ = x[Flashlight-2343591895]
	_ = x[GolfClub-1141786504]
	_ = x[Hammer-1317494643]
	_ = x[Hatchet-4191993645]
	_ = x[BrassKnuckles-3638508604]
	_ = x[Knife-2578778090]
	_ = x[Machete-3713923289]
	_ = x[Switchblade-3756226112]
	_ = x[Nightstick-1737195953]
	_ = x[PipeWrench-419712736]
	_ = x[BattleAxe-3441901897]
	_ = x[PoolCue-2484171525]
	_ = x[StoneHatchet-940833800]
	_ = x[Pistol-453432689]
	_ = x[PistolMkII-3219281620]
	_ = x[CombatPistol-1593441988]
	_ = x[APPistol-584646201]
	_ = x[StunGun-911657153]
	_ = x[Pistol50-2578377531]
	_ = x[SNSPistol-3218215474]
	_ = x[SNSPistolMkII-2285322324]
	_ = x[HeavyPistol-3523564046]
	_ = x[VintagePistol-137902532]
	_ = x[FlareGun-1198879012]
	_ = x[MarksmanPistol-3696079510]
	_ = x[HeavyRevolver-3249783761]
	_ = x[HeavyRevolverMkII-3415619887]
	_ = x[DoubleActionRevolver-2548703416]
	_ = x[UpnAtomizer-2939590305]
	_ = x[MicroSMG-324215364]
	_ = x[SMG-736523883]
	_ = x[SMGMkII-2024373456]
	_ = x[AssaultSMG-4024951519]
	_ = x[CombatPDW-171789620]
	_ = x[MachinePistol-3675956304]
	_ = x[MiniSMG-3173288789]
	_ = x[UnholyHellbringer-1198256469]
	_ = x[PumpShotgun-487013001]
	_ = x[PumpShotgunMkII-1432025498]
	_ = x[SawedOffShotgun-2017895192]
	_ = x[AssaultShotgun-3800352039]
	_ = x[BullpupShotgun-2640438543]
	_ = x[Musket-2828843422]
	_ = x[HeavyShotgun-984333226]
	_ = x[DoubleBarrelShotgun-4019527611]
	_ = x[SweeperShotgun-317205821]
	_ = x[AssaultRifle-3220176749]
	_ = x[AssaultRifleMkII-961495388]
	_ = x[CarbineRifle-2210333304]
	_ = x[CarbineRifleMkII-4208062921]
	_ = x[AdvancedRifle-2937143193]
	_ = x[SpecialCarbine-3231910285]
	_ = x[SpecialCarbineMkII-2526821735]
	_ = x[BullpupRifle-2132975508]
	_ = x[BullpupRifleMkII-2228681469]
	_ = x[CompactRifle-1649403952]
	_ = x[MG-2634544996]
	_ = x[CombatMG-2144741730]
	_ = x[CombatMGMkII-3686625920]
	_ = x[GusenbergSweeper-1627465347]
	_ = x[SniperRifle-100416529]
	_ = x[HeavySniper-205991906]
	_ = x[HeavySniperMkII-177293209]
	_ = x[MarksmanRifle-3342088282]
	_ = x[MarksmanRifleMkII-1785463520]
	_ = x[RPG-2982836145]
	_ = x[GrenadeLauncher-2726580491]
	_ = x[GrenadeLauncherSmoke-1305664598]
	_ = x[Minigun-1119849093]
	_ = x[FireworkLauncher-2138347493]
	_ = x[Railgun-1834241177]
	_ = x[HomingLauncher-1672152130]
	_ = x[Widowmaker-3056410471]
	_ = x[Grenade-2481070269]
	_ = x[BZGas-2694266206]
	_ = x[MolotovCocktail-615608432]
	_ = x[StickyBomb-741814745]
	_ = x[ProximityMines-2874559379]
	_ = x[Snowballs-126349499]
	_ = x[PipeBombs-3125143736]
	_ = x[Baseball-600439132]
	_ = x[TearGas-4256991824]
	_ = x[Flare-1233104067]
	_ = x[JerryCan-883325847]
	_ = x[Parachute-4222310262]
	_ = x[FireExtinguisher-101631238]
	_ = x[GadgetPistol-1470379660]
	_ = x[MilitaryRifle-2636060646]
	_ = x[CombatShotgun-94989220]
	_ = x[Fertilizercan-406929569]
	_ = x[HeavyRifle-3347935668]
	_ = x[EMPLauncher-3676729658]
	_ = x[CeramicPistol-727643628]
	_ = x[NavyRevolver-2441047180]
	_ = x[HazardCan-3126027122]
	_ = x[TacticalRifle-3520460075]
	_ = x[MetalDetector-3684886537]
	_ = x[PrecisionRifle-1853742572]
	_ = x[CandyCane-1703483498]
	_ = x[AcidPackage-4159824478]
	_ = x[Wm29Pistol-465894841]
	_ = x[RailgunXm3-4272043364]
	_ = x[TecPistol-350597077]
	_ = x[BattleRifle-1924557585]
	_ = x[SnowLauncher-62870901]
	_ = x[HackingDevice-485882440]
	_ = x[Stunrod-3670016037]
}

const _ModelHash_name = "SnowLauncherCombatShotgunSniperRifleFireExtinguisherSnowballsVintagePistolCombatPDWHeavySniperMkIIHeavySniperSweeperShotgunMicroSMGTecPistolFertilizercanPipeWrenchPistolWm29PistolHackingDevicePumpShotgunAPPistolBaseballMolotovCocktailCeramicPistolSMGStickyBombJerryCanStunGunStoneHatchetAssaultRifleMkIIHeavyShotgunMinigunGolfClubUnholyHellbringerFlareGunFlareGrenadeLauncherSmokeHammerPumpShotgunMkIIGadgetPistolCombatPistolGusenbergSweeperCompactRifleHomingLauncherCandyCaneNightstickMarksmanRifleMkIIRailgunPrecisionRifleBattleRifleSawedOffShotgunSMGMkIIBullpupRifleFireworkLauncherCombatMGCarbineRifleCrowbarBullpupRifleMkIISNSPistolMkIIFlashlightNavyRevolverAntiqueCavalryDaggerGrenadePoolCueBaseballBatSpecialCarbineMkIIDoubleActionRevolverPistol50KnifeMGMilitaryRifleBullpupShotgunBZGasFistGrenadeLauncherMusketProximityMinesAdvancedRifleUpnAtomizerRPGWidowmakerPipeBombsHazardCanMiniSMGSNSPistolPistolMkIIAssaultRifleSpecialCarbineHeavyRevolverMarksmanRifleHeavyRifleHeavyRevolverMkIIBattleAxeTacticalRifleHeavyPistolBrassKnucklesStunrodMachinePistolEMPLauncherMetalDetectorCombatMGMkIIMarksmanPistolMacheteSwitchbladeAssaultShotgunDoubleBarrelShotgunAssaultSMGAcidPackageHatchetBrokenBottleCarbineRifleMkIIParachuteTearGasRailgunXm3"

var _ModelHash_map = map[ModelHash]string{
	62870901:   _ModelHash_name[0:12],
	94989220:   _ModelHash_name[12:25],
	100416529:  _ModelHash_name[25:36],
	101631238:  _ModelHash_name[36:52],
	126349499:  _ModelHash_name[52:61],
	137902532:  _ModelHash_name[61:74],
	171789620:  _ModelHash_name[74:83],
	177293209:  _ModelHash_name[83:98],
	205991906:  _ModelHash_name[98:109],
	317205821:  _ModelHash_name[109:123],
	324215364:  _ModelHash_name[123:131],
	350597077:  _ModelHash_name[131:140],
	406929569:  _ModelHash_name[140:153],
	419712736:  _ModelHash_name[153:163],
	453432689:  _ModelHash_name[163:169],
	465894841:  _ModelHash_name[169:179],
	485882440:  _ModelHash_name[179:192],
	487013001:  _ModelHash_name[192:203],
	584646201:  _ModelHash_name[203:211],
	600439132:  _ModelHash_name[211:219],
	615608432:  _ModelHash_name[219:234],
	727643628:  _ModelHash_name[234:247],
	736523883:  _ModelHash_name[247:250],
	741814745:  _ModelHash_name[250:260],
	883325847:  _ModelHash_name[260:268],
	911657153:  _ModelHash_name[268:275],
	940833800:  _ModelHash_name[275:287],
	961495388:  _ModelHash_name[287:303],
	984333226:  _ModelHash_name[303:315],
	1119849093: _ModelHash_name[315:322],
	1141786504: _ModelHash_name[322:330],
	1198256469: _ModelHash_name[330:347],
	1198879012: _ModelHash_name[347:355],
	1233104067: _ModelHash_name[355:360],
	1305664598: _ModelHash_name[360:380],
	1317494643: _ModelHash_name[380:386],
	1432025498: _ModelHash_name[386:401],
	1470379660: _ModelHash_name[401:413],
	1593441988: _ModelHash_name[413:425],
	1627465347: _ModelHash_name[425:441],
	1649403952: _ModelHash_name[441:453],
	1672152130: _ModelHash_name[453:467],
	1703483498: _ModelHash_name[467:476],
	1737195953: _ModelHash_name[476:486],
	1785463520: _ModelHash_name[486:503],
	1834241177: _ModelHash_name[503:510],
	1853742572: _ModelHash_name[510:524],
	1924557585: _ModelHash_name[524:535],
	2017895192: _ModelHash_name[535:550],
	2024373456: _ModelHash_name[550:557],
	2132975508: _ModelHash_name[557:569],
	2138347493: _ModelHash_name[569:585],
	2144741730: _ModelHash_name[585:593],
	2210333304: _ModelHash_name[593:605],
	2227010557: _ModelHash_name[605:612],
	2228681469: _ModelHash_name[612:628],
	2285322324: _ModelHash_name[628:641],
	2343591895: _ModelHash_name[641:651],
	2441047180: _ModelHash_name[651:663],
	2460120199: _ModelHash_name[663:683],
	2481070269: _ModelHash_name[683:690],
	2484171525: _ModelHash_name[690:697],
	2508868239: _ModelHash_name[697:708],
	2526821735: _ModelHash_name[708:726],
	2548703416: _ModelHash_name[726:746],
	2578377531: _ModelHash_name[746:754],
	2578778090: _ModelHash_name[754:759],
	2634544996: _ModelHash_name[759:761],
	2636060646: _ModelHash_name[761:774],
	2640438543: _ModelHash_name[774:788],
	2694266206: _ModelHash_name[788:793],
	2725352035: _ModelHash_name[793:797],
	2726580491: _ModelHash_name[797:812],
	2828843422: _ModelHash_name[812:818],
	2874559379: _ModelHash_name[818:832],
	2937143193: _ModelHash_name[832:845],
	2939590305: _ModelHash_name[845:856],
	2982836145: _ModelHash_name[856:859],
	3056410471: _ModelHash_name[859:869],
	3125143736: _ModelHash_name[869:878],
	3126027122: _ModelHash_name[878:887],
	3173288789: _ModelHash_name[887:894],
	3218215474: _ModelHash_name[894:903],
	3219281620: _ModelHash_name[903:913],
	3220176749: _ModelHash_name[913:925],
	3231910285: _ModelHash_name[925:939],
	3249783761: _ModelHash_name[939:952],
	3342088282: _ModelHash_name[952:965],
	3347935668: _ModelHash_name[965:975],
	3415619887: _ModelHash_name[975:992],
	3441901897: _ModelHash_name[992:1001],
	3520460075: _ModelHash_name[1001:1014],
	3523564046: _ModelHash_name[1014:1025],
	3638508604: _ModelHash_name[1025:1038],
	3670016037: _ModelHash_name[1038:1045],
	3675956304: _ModelHash_name[1045:1058],
	3676729658: _ModelHash_name[1058:1069],
	3684886537: _ModelHash_name[1069:1082],
	3686625920: _ModelHash_name[1082:1094],
	3696079510: _ModelHash_name[1094:1108],
	3713923289: _ModelHash_name[1108:1115],
	3756226112: _ModelHash_name[1115:1126],
	3800352039: _ModelHash_name[1126:1140],
	4019527611: _ModelHash_name[1140:1159],
	4024951519: _ModelHash_name[1159:1169],
	4159824478: _ModelHash_name[1169:1180],
	4191993645: _ModelHash_name[1180:1187],
	4192643659: _ModelHash_name[1187:1199],
	4208062921: _ModelHash_name[1199:1215],
	4222310262: _ModelHash_name[1215:1224],
	4256991824: _ModelHash_name[1224:1231],
	4272043364: _ModelHash_name[1231:1241],
}

func (i ModelHash) String() string {
	if str, ok := _ModelHash_map[i]; ok {
		return str
	}
	return "ModelHash(" + strconv.FormatInt(int64(i), 10) + ")"
}
