// Code generated by "stringer -type=VehicleDoorType"; DO NOT EDIT.

package vehicle_door_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DriverFront-0]
	_ = x[PassengerFront-1]
	_ = x[DriverRear-2]
	_ = x[PassengerRear-3]
	_ = x[Hood-4]
	_ = x[Trunk-5]
}

const _VehicleDoorType_name = "DriverFrontPassengerFrontDriverRearPassengerRearHoodTrunk"

var _VehicleDoorType_index = [...]uint8{0, 11, 25, 35, 48, 52, 57}

func (i VehicleDoorType) String() string {
	if i >= VehicleDoorType(len(_VehicleDoorType_index)-1) {
		return "VehicleDoorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VehicleDoorType_name[_VehicleDoorType_index[i]:_VehicleDoorType_index[i+1]]
}
