// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Player-0]
	_ = x[Vehicle-1]
	_ = x[Ped-2]
	_ = x[Blip-3]
	_ = x[Colshape-4]
	_ = x[Object-5]
	_ = x[CheckPoint-6]
	_ = x[Marker-7]
}

const _ObjectType_name = "PlayerVehiclePedBlipColshapeObjectCheckPointMarker"

var _ObjectType_index = [...]uint8{0, 6, 13, 16, 20, 28, 34, 44, 50}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
