// Code generated by "stringer -type=AmmoHash"; DO NOT EDIT.

package ammo_type

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AmmoHashNull-987444055]
	_ = x[AmmoHashShotgun-2416459067]
	_ = x[AmmoHashSniper-1285032059]
	_ = x[AmmoHashFireExtinguisher-1359393852]
	_ = x[AmmoHashGrenadeLauncher-1003267566]
	_ = x[AmmoHashSnowball-2182627693]
	_ = x[AmmoHashPistol-1950175060]
	_ = x[AmmoHashSmg-1820140472]
	_ = x[AmmoHashFertilizerCan-1963932634]
	_ = x[AmmoHashBall-4287981158]
	_ = x[AmmoHashMolotov-1446246869]
	_ = x[AmmoHashStickyBomb-1411692055]
	_ = x[AmmoHashPetrolCan-3395492001]
	_ = x[AmmoHashStunGun-2955849184]
	_ = x[AmmoHashRifle-218444191]
	_ = x[AmmoHashMinigun-2680539266]
	_ = x[AmmoHashMG-1788949567]
	_ = x[AmmoHashFlareGun-1173416293]
	_ = x[AmmoHashFlare-1808594799]
	_ = x[AmmoHashGrenadeLauncherSmoke-826266432]
	_ = x[AmmoHashHomingLauncher-2568293933]
	_ = x[AmmoHashRailgun-2034517757]
	_ = x[AmmoHashFirework-2938367503]
	_ = x[AmmoHashGrenade-1003688881]
	_ = x[AmmoHashBZGas-2608103076]
	_ = x[AmmoHashProximityMine-2938243239]
	_ = x[AmmoHashRayPistol-2768943988]
	_ = x[AmmoHashRpg-1742569970]
	_ = x[AmmoHashPipeBomb-357983224]
	_ = x[AmmoHashHazardCan-1618528319]
	_ = x[AmmoHashEMPLauncher-4057942205]
	_ = x[AmmoHashAcidPackage-1003730930]
	_ = x[AmmoHashSmokeGrenade-3859679398]
	_ = x[AmmoHashRailgunXm3-1322889087]
}

const _AmmoHash_name = "AmmoHashRifleAmmoHashPipeBombAmmoHashGrenadeLauncherSmokeAmmoHashNullAmmoHashGrenadeLauncherAmmoHashGrenadeAmmoHashAcidPackageAmmoHashFlareGunAmmoHashSniperAmmoHashRailgunXm3AmmoHashFireExtinguisherAmmoHashStickyBombAmmoHashMolotovAmmoHashHazardCanAmmoHashRpgAmmoHashMGAmmoHashFlareAmmoHashSmgAmmoHashPistolAmmoHashFertilizerCanAmmoHashRailgunAmmoHashSnowballAmmoHashShotgunAmmoHashHomingLauncherAmmoHashBZGasAmmoHashMinigunAmmoHashRayPistolAmmoHashProximityMineAmmoHashFireworkAmmoHashStunGunAmmoHashPetrolCanAmmoHashSmokeGrenadeAmmoHashEMPLauncherAmmoHashBall"

var _AmmoHash_map = map[AmmoHash]string{
	218444191:  _AmmoHash_name[0:13],
	357983224:  _AmmoHash_name[13:29],
	826266432:  _AmmoHash_name[29:57],
	987444055:  _AmmoHash_name[57:69],
	1003267566: _AmmoHash_name[69:92],
	1003688881: _AmmoHash_name[92:107],
	1003730930: _AmmoHash_name[107:126],
	1173416293: _AmmoHash_name[126:142],
	1285032059: _AmmoHash_name[142:156],
	1322889087: _AmmoHash_name[156:174],
	1359393852: _AmmoHash_name[174:198],
	1411692055: _AmmoHash_name[198:216],
	1446246869: _AmmoHash_name[216:231],
	1618528319: _AmmoHash_name[231:248],
	1742569970: _AmmoHash_name[248:259],
	1788949567: _AmmoHash_name[259:269],
	1808594799: _AmmoHash_name[269:282],
	1820140472: _AmmoHash_name[282:293],
	1950175060: _AmmoHash_name[293:307],
	1963932634: _AmmoHash_name[307:328],
	2034517757: _AmmoHash_name[328:343],
	2182627693: _AmmoHash_name[343:359],
	2416459067: _AmmoHash_name[359:374],
	2568293933: _AmmoHash_name[374:396],
	2608103076: _AmmoHash_name[396:409],
	2680539266: _AmmoHash_name[409:424],
	2768943988: _AmmoHash_name[424:441],
	2938243239: _AmmoHash_name[441:462],
	2938367503: _AmmoHash_name[462:478],
	2955849184: _AmmoHash_name[478:493],
	3395492001: _AmmoHash_name[493:510],
	3859679398: _AmmoHash_name[510:530],
	4057942205: _AmmoHash_name[530:549],
	4287981158: _AmmoHash_name[549:561],
}

func (i AmmoHash) String() string {
	if str, ok := _AmmoHash_map[i]; ok {
		return str
	}
	return "AmmoHash(" + strconv.FormatInt(int64(i), 10) + ")"
}
